name: Docker Build and Test

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with: 
          username: sanjana257
          password: catisgay.25

                              
    - name: Build Docker image
      run: docker build -t sanjana257/weeeeb-php-env .

    - name: Run Docker Compose
      run: docker-compose up --build -d

    - name: Wait for services to start
      run: sleep 10  # Adjust the wait time as needed
      
    - name: Push Docker Image
      run: docker push sanjana257/weeeeb-php-env:latest

    - name: Stop Docker Compose
      run: docker-compose down
